version: '3.8'
services:
  webapplication1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 49845:80
    environment:
      - DATABASE_CONNECTION_STRING=mongodb+srv://tnyamuda:tat1755@cluster0.vpaqxqq.mongodb.net/?retryWrites=true&w=majority
      - DATABASE_NAME=school_locator
